-- Add missing columns that were added to schema but not migrated
-- This migration captures schema changes from tasks 43, 50, 52, 53, 54

-- ============================================================================
-- League: Sync tracking fields (task-50)
-- ============================================================================
ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "lastSyncedAt" TIMESTAMP(3);
ALTER TABLE "League" ADD COLUMN IF NOT EXISTS "lastSyncChecksum" VARCHAR(64);

-- ============================================================================
-- Team: Platform-specific identifier (task-50)
-- ============================================================================
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "platformTeamId" VARCHAR(255);

-- ============================================================================
-- LeagueSettings: Feature toggles and auto-moment settings (task-53)
-- ============================================================================
ALTER TABLE "LeagueSettings" ADD COLUMN IF NOT EXISTS "playoffBracketEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "LeagueSettings" ADD COLUMN IF NOT EXISTS "momentsEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "LeagueSettings" ADD COLUMN IF NOT EXISTS "transactionsEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "LeagueSettings" ADD COLUMN IF NOT EXISTS "autoMomentsEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "LeagueSettings" ADD COLUMN IF NOT EXISTS "blowoutThreshold" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "LeagueSettings" ADD COLUMN IF NOT EXISTS "closeGameThreshold" INTEGER NOT NULL DEFAULT 1;

-- ============================================================================
-- Moment: Moderation and auto-generation fields (task-53)
-- ============================================================================
ALTER TABLE "Moment" ADD COLUMN IF NOT EXISTS "hideReason" VARCHAR(255);
ALTER TABLE "Moment" ADD COLUMN IF NOT EXISTS "hiddenAt" TIMESTAMP(3);
ALTER TABLE "Moment" ADD COLUMN IF NOT EXISTS "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Moment" ADD COLUMN IF NOT EXISTS "momentType" VARCHAR(50);
ALTER TABLE "Moment" ADD COLUMN IF NOT EXISTS "metadata" JSONB;
ALTER TABLE "Moment" ADD COLUMN IF NOT EXISTS "sourceMatchupId" TEXT;
ALTER TABLE "Moment" ADD COLUMN IF NOT EXISTS "sourceTransactionId" TEXT;

-- CreateIndex for Moment auto-generation
CREATE INDEX IF NOT EXISTS "Moment_leagueId_isAutoGenerated_idx" ON "Moment"("leagueId", "isAutoGenerated");
CREATE INDEX IF NOT EXISTS "Moment_leagueId_sourceMatchupId_momentType_idx" ON "Moment"("leagueId", "sourceMatchupId", "momentType");
CREATE INDEX IF NOT EXISTS "Moment_leagueId_sourceTransactionId_momentType_idx" ON "Moment"("leagueId", "sourceTransactionId", "momentType");

-- ============================================================================
-- Matchup: Playoff and stat correction fields (task-43, task-52)
-- ============================================================================
ALTER TABLE "Matchup" ADD COLUMN IF NOT EXISTS "homeScore" DOUBLE PRECISION;
ALTER TABLE "Matchup" ADD COLUMN IF NOT EXISTS "awayScore" DOUBLE PRECISION;
ALTER TABLE "Matchup" ADD COLUMN IF NOT EXISTS "isPlayoff" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Matchup" ADD COLUMN IF NOT EXISTS "playoffRound" INTEGER;
ALTER TABLE "Matchup" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
ALTER TABLE "Matchup" ADD COLUMN IF NOT EXISTS "lastScoreUpdate" TIMESTAMP(3);
ALTER TABLE "Matchup" ADD COLUMN IF NOT EXISTS "statCorrectionAt" TIMESTAMP(3);
ALTER TABLE "Matchup" ADD COLUMN IF NOT EXISTS "previousWinnerId" TEXT;

-- Update default for season column
ALTER TABLE "Matchup" ALTER COLUMN "season" SET DEFAULT 2025;

-- CreateIndex for Matchup playoff queries
CREATE INDEX IF NOT EXISTS "Matchup_leagueId_isPlayoff_idx" ON "Matchup"("leagueId", "isPlayoff");
CREATE INDEX IF NOT EXISTS "Matchup_leagueId_isPlayoff_playoffRound_idx" ON "Matchup"("leagueId", "isPlayoff", "playoffRound");

-- ============================================================================
-- Transaction: Auto-moment and promotion fields (task-53, task-54)
-- ============================================================================
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "playerPosition" VARCHAR(10);
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "isNotable" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "impactScore" DOUBLE PRECISION;
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "isPromoted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "promotedMomentId" TEXT;

-- CreateIndex for Transaction promotion queries
CREATE INDEX IF NOT EXISTS "Transaction_leagueId_isNotable_idx" ON "Transaction"("leagueId", "isNotable");
CREATE INDEX IF NOT EXISTS "Transaction_leagueId_isPromoted_impactScore_idx" ON "Transaction"("leagueId", "isPromoted", "impactScore");

-- ============================================================================
-- SeasonHistory: Additional stats fields (task-14)
-- ============================================================================
ALTER TABLE "SeasonHistory" ADD COLUMN IF NOT EXISTS "playoffTeams" INTEGER;
ALTER TABLE "SeasonHistory" ADD COLUMN IF NOT EXISTS "highestWeeklyScore" DOUBLE PRECISION;
