// tests/backend/be-task-54.test.ts
// Backend Test: Implement Transaction Promotion Job

import { describe, test, expect, afterEach } from 'vitest';
import { prisma } from '@/lib/db';
import {
  calculateImpactScore,
  getPositionValue,
  generateHypeText,
  generateTradeHypeText,
  generateWaiverHypeText,
  generateDropHypeText,
} from '@/jobs/promote-transactions';

describe('Backend: Implement Transaction Promotion Job (task-54)', () => {
  let testLeagueId: string | null = null;
  let testUserId: string | null = null;
  let testTeamIds: string[] = [];

  afterEach(async () => {
    await prisma.moment?.deleteMany({ where: { leagueId: testLeagueId || '' } }).catch(() => {});
    await prisma.transaction?.deleteMany({ where: { leagueId: testLeagueId || '' } }).catch(() => {});
    for (const teamId of testTeamIds) {
      await prisma.team?.delete({ where: { id: teamId } }).catch(() => {});
    }
    testTeamIds = [];
    if (testLeagueId) {
      await prisma.league?.delete({ where: { id: testLeagueId } }).catch(() => {});
      testLeagueId = null;
    }
    if (testUserId) {
      await prisma.user.delete({ where: { id: testUserId } }).catch(() => {});
      testUserId = null;
    }
  });

  test('analyzes transaction impact (playoff implications, rivalry trades)', async () => {
    const league = await prisma.league?.create({
      data: {
        slug: 'test_promo_impact',
        name: 'TEST_Promo Impact',
        platform: 'sleeper',
        season: 2025,
        visibility: 'public',
      },
    });
    testLeagueId = league?.id || null;

    // Create test teams
    const team1 = await prisma.team?.create({
      data: { leagueId: league!.id, name: 'Contender 1' },
    });
    const team2 = await prisma.team?.create({
      data: { leagueId: league!.id, name: 'Rebuilding Team' },
    });
    testTeamIds.push(team1!.id, team2!.id);

    // High-impact trade (playoff contender to contender)
    const playoffTrade = await prisma.transaction?.create({
      data: {
        leagueId: league!.id,
        teamId: team1!.id,
        type: 'trade',
        playerName: 'Star WR',
        playerPosition: 'WR',
        weekNumber: 12, // Late season - playoff implications
        tradePartnerTeamId: team1!.id, // Self for simplicity
        impactScore: 9.5, // High impact
        timestamp: new Date(),
      },
    });

    // Low-impact transaction
    const lowImpact = await prisma.transaction?.create({
      data: {
        leagueId: league!.id,
        teamId: team2!.id,
        type: 'add',
        playerName: 'Practice Squad Player',
        playerPosition: 'WR',
        weekNumber: 12,
        impactScore: 1.5, // Low impact
        timestamp: new Date(),
      },
    });

    // Filter high-impact transactions
    const impactThreshold = 7.0;
    const highImpactTransactions = await prisma.transaction?.findMany({
      where: {
        leagueId: league!.id,
        impactScore: { gte: impactThreshold },
      },
    });

    expect(highImpactTransactions?.length).toBe(1);
    expect(highImpactTransactions?.[0].playerName).toBe('Star WR');
  });

  test('promotes high-impact transactions to moments', async () => {
    const user = await prisma.user.create({
      data: { email: 'TEST_promo_moment@example.com', name: 'TEST_PromoMoment' },
    });
    testUserId = user.id;

    const league = await prisma.league?.create({
      data: {
        slug: 'test_promo_moment',
        name: 'TEST_Promo Moment',
        platform: 'sleeper',
        season: 2025,
        visibility: 'public',
      },
    });
    testLeagueId = league?.id || null;

    // Create test team
    const team = await prisma.team?.create({
      data: { leagueId: league!.id, name: 'Test Team 1' },
    });
    testTeamIds.push(team!.id);

    // High-impact transaction
    const transaction = await prisma.transaction?.create({
      data: {
        leagueId: league!.id,
        teamId: team!.id,
        type: 'trade',
        playerName: 'Patrick Mahomes',
        playerPosition: 'QB',
        weekNumber: 10,
        impactScore: 10,
        isPromoted: false,
        timestamp: new Date(),
      },
    });

    // Promote to moment
    const moment = await prisma.moment?.create({
      data: {
        leagueId: league!.id,
        authorId: user.id,
        content: '💰 BLOCKBUSTER! Patrick Mahomes on the move!',
        isAutoGenerated: true,
        momentType: 'transaction_promotion',
        sourceTransactionId: transaction!.id,
      },
    });

    // Mark transaction as promoted
    await prisma.transaction?.update({
      where: { id: transaction!.id },
      data: { isPromoted: true, promotedMomentId: moment!.id },
    });

    const promotedTransaction = await prisma.transaction?.findUnique({
      where: { id: transaction!.id },
    });

    expect(promotedTransaction?.isPromoted).toBe(true);
    expect(promotedTransaction?.promotedMomentId).toBe(moment!.id);
  });

  test('adds context and hype text', async () => {
    // Test the actual implementation functions
    const tradeHype = generateTradeHypeText('Patrick Mahomes', 'Team A', 'Team B', 13, true, false);
    const waiverHype = generateWaiverHypeText('Hidden Gem RB', 'Team C', 75);
    const dropHype = generateDropHypeText('Former Star WR', 'Team D');

    // Trade hype text should contain expected elements
    expect(tradeHype).toContain('Patrick Mahomes');
    expect(tradeHype).toContain('Team A');
    expect(tradeHype).toContain('Team B');

    // Waiver hype text should contain expected elements
    expect(waiverHype).toContain('Hidden Gem RB');
    expect(waiverHype).toContain('Team C');
    expect(waiverHype).toContain('$75'); // FAAB amount

    // Drop hype text should contain expected elements
    expect(dropHype).toContain('SHOCKING DROP');
    expect(dropHype).toContain('Former Star WR');
  });

  test('posted to league feed with transaction metadata', async () => {
    const user = await prisma.user.create({
      data: { email: 'TEST_promo_feed@example.com', name: 'TEST_PromoFeed' },
    });
    testUserId = user.id;

    const league = await prisma.league?.create({
      data: {
        slug: 'test_promo_feed',
        name: 'TEST_Promo Feed',
        platform: 'sleeper',
        season: 2025,
        visibility: 'public',
      },
    });
    testLeagueId = league?.id || null;

    // Create test teams
    const team1 = await prisma.team?.create({
      data: { leagueId: league!.id, name: 'Test Team 1' },
    });
    const team2 = await prisma.team?.create({
      data: { leagueId: league!.id, name: 'Test Team 2' },
    });
    testTeamIds.push(team1!.id, team2!.id);

    const transaction = await prisma.transaction?.create({
      data: {
        leagueId: league!.id,
        teamId: team1!.id,
        type: 'trade',
        playerName: 'Star Player',
        playerPosition: 'WR',
        weekNumber: 10,
        tradePartnerTeamId: team2!.id,
        timestamp: new Date(),
      },
    });

    // Create moment with transaction metadata
    const moment = await prisma.moment?.create({
      data: {
        leagueId: league!.id,
        authorId: user.id,
        content: '💰 TRADE ALERT: Star Player traded!',
        isAutoGenerated: true,
        momentType: 'transaction_promotion',
        sourceTransactionId: transaction!.id,
        metadata: {
          transactionId: transaction!.id,
          transactionType: 'trade',
          playerName: 'Star Player',
          fromTeamId: team1!.id,
          toTeamId: team2!.id,
          weekNumber: 10,
        },
      },
    });

    expect(moment?.sourceTransactionId).toBe(transaction!.id);
    expect(moment?.metadata).toBeDefined();
    expect((moment?.metadata as any)?.transactionType).toBe('trade');
  });

  test('calculates impact score correctly', async () => {
    // Test using the actual implementation
    const highImpact = calculateImpactScore({
      playerValue: 8,
      weekNumber: 13,
      isPlayoffContender: true,
      isRivalryTrade: true,
      transactionType: 'trade',
    });

    const lowImpact = calculateImpactScore({
      playerValue: 3,
      weekNumber: 5,
      isPlayoffContender: false,
      isRivalryTrade: false,
      transactionType: 'add',
    });

    expect(highImpact).toBe(10); // Capped at max
    expect(lowImpact).toBeLessThan(5);

    // Test position values
    expect(getPositionValue('QB')).toBe(9);
    expect(getPositionValue('RB')).toBe(8);
    expect(getPositionValue('WR')).toBe(7);
    expect(getPositionValue('K')).toBe(3);
  });

  test('does not promote already-promoted transactions', async () => {
    const user = await prisma.user.create({
      data: { email: 'TEST_promo_dedupe@example.com', name: 'TEST_PromoDedupe' },
    });
    testUserId = user.id;

    const league = await prisma.league?.create({
      data: {
        slug: 'test_promo_dedupe',
        name: 'TEST_Promo Dedupe',
        platform: 'sleeper',
        season: 2025,
        visibility: 'public',
      },
    });
    testLeagueId = league?.id || null;

    // Create test team
    const team = await prisma.team?.create({
      data: { leagueId: league!.id, name: 'Test Team' },
    });
    testTeamIds.push(team!.id);

    // Already-promoted transaction
    const transaction = await prisma.transaction?.create({
      data: {
        leagueId: league!.id,
        teamId: team!.id,
        type: 'trade',
        playerName: 'Already Promoted Player',
        weekNumber: 10,
        impactScore: 9,
        isPromoted: true,
        timestamp: new Date(),
      },
    });

    // Query for unpromoted high-impact transactions
    const unpromotedTransactions = await prisma.transaction?.findMany({
      where: {
        leagueId: league!.id,
        impactScore: { gte: 7 },
        isPromoted: false,
      },
    });

    expect(unpromotedTransactions?.length).toBe(0);
  });

  test('handles multiple transaction types', async () => {
    const league = await prisma.league?.create({
      data: {
        slug: 'test_promo_types',
        name: 'TEST_Promo Types',
        platform: 'sleeper',
        season: 2025,
        visibility: 'public',
      },
    });
    testLeagueId = league?.id || null;

    // Create test team
    const team = await prisma.team?.create({
      data: { leagueId: league!.id, name: 'Test Team' },
    });
    testTeamIds.push(team!.id);

    const transactionTypes = ['trade', 'add', 'drop', 'waiver'];

    for (const type of transactionTypes) {
      await prisma.transaction?.create({
        data: {
          leagueId: league!.id,
          teamId: team!.id,
          type: type,
          playerName: `TEST_${type} Player`,
          weekNumber: 10,
          impactScore: 8,
          timestamp: new Date(),
        },
      });
    }

    const allTransactions = await prisma.transaction?.findMany({
      where: { leagueId: league!.id },
    });

    expect(allTransactions?.length).toBe(4);
    expect(allTransactions?.map((t) => t.type).sort()).toEqual(transactionTypes.sort());
  });

  test('generates correct hype text for different scenarios', () => {
    // Test rivalry trade
    const rivalryHype = generateHypeText('trade', 'Elite RB', 'Team A', 'Team B', 12, false, true);
    expect(rivalryHype).toContain('RIVALRY');
    expect(rivalryHype).toContain('Elite RB');

    // Test playoff impact trade
    const playoffHype = generateHypeText('trade', 'Star QB', 'Team C', 'Team D', 14, true, false);
    expect(playoffHype).toContain('Star QB');

    // Test championship push (week 13+)
    const championshipHype = generateTradeHypeText('Superstar', 'Team E', 'Team F', 15, false, false);
    expect(championshipHype).toContain('CHAMPIONSHIP');

    // Test big FAAB waiver
    const bigFaabHype = generateWaiverHypeText('Hot Pickup', 'Team G', 80);
    expect(bigFaabHype).toContain('ALL-IN');
    expect(bigFaabHype).toContain('$80');

    // Test regular waiver
    const regularWaiverHype = generateWaiverHypeText('Depth Player', 'Team H', 25);
    expect(regularWaiverHype).toContain('WAIVER WIRE');
  });
});
